# Generated by Django 5.1.5 on 2025-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipper_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
