# Generated by Django 5.1.5 on 2025-02-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_refund_refund_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='bank_name',
            field=models.CharField(choices=[('KBANK', 'ธนาคารกสกรไทย'), ('BBL', 'ธนาคารกรงเทพ'), ('KTB', 'ธนาคารกรงไทย'), ('GSB', 'ธนาคารออมสน')], default='bank', max_length=10),
        ),
    ]
