# Generated by Django 5.1.5 on 2025-02-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_refund_bank_name_alter_refund_refund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
            preserve_default=False,
        ),
    ]
