# Generated by Django 5.1.5 on 2025-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
