# Generated by Django 5.1.6 on 2025-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="claim_contact",
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_status",
            field=models.CharField(default="กำลังดำเนินการ", max_length=255),
        ),
        migrations.AlterField(
            model_name="claim",
            name="promtpay_number",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=1),
        ),
    ]
