# Generated by Django 5.1.5 on 2025-02-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_name', models.CharField(max_length=255)),
                ('promotion_type', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('promotion_image', models.ImageField(blank=True, null=True, upload_to='promotion_image/')),
            ],
            options={
                'db_table': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TransactionType',
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promotion')),
            ],
            options={
                'db_table': 'PromotionProduct',
            },
        ),
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('recommended_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'RecommendedProduct',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.admin')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('transaction_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transactiontype')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('favorite_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('favorite_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'FavoriteProduct',
                'unique_together': {('product_id', 'user_id')},
            },
        ),
    ]
