# Generated by Django 5.1.6 on 2025-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(default='กำลังดำเนินการ', max_length=255),
        ),
    ]
