# Generated by Django 5.1.5 on 2025-02-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cart_product_alter_cartitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
