# Generated by Django 5.1.5 on 2025-04-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('claim_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ClaimStatus',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('delivery_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'DeliveryStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PaymentStatus',
            },
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'รายการในตะกร้า', 'verbose_name_plural': 'รายการในตะกร้า'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.claimstatus'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paymentstatus'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(blank=True, choices=[('bank', 'Bank Account'), ('promptpay', 'PromptPay')], max_length=10, null=True)),
                ('bank_name', models.CharField(blank=True, choices=[('KBANK', 'ธนาคารกสิกรไทย'), ('BBL', 'ธนาคารกรุงเทพ'), ('KTB', 'ธนาคารกรุงไทย'), ('GSB', 'ธนาคารออมสิน')], max_length=10, null=True)),
                ('refund_number', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
