# Generated by Django 5.1.5 on 2025-02-19 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_promotion_transactiontype_promotionproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='Promotion_image',
            new_name='promotion_image',
        ),
        migrations.RenameField(
            model_name='recommendedproduct',
            old_name='Recommended_date',
            new_name='recommended_date',
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='favorite_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
