# Generated by Django 5.1.5 on 2025-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'รายการในตะกร้า', 'verbose_name_plural': 'รายการในตะกร้า'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
