# Generated by Django 5.1.5 on 2025-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cartitem_options_cartitem_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
