# Generated by Django 5.1.5 on 2025-02-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='account_number',
            new_name='refund_number',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='promptpay_number',
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(default='bank', max_length=10),
        ),
    ]
