# Generated by Django 5.1.5 on 2025-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_account_number_refund_refund_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('promptpay', 'PromptPay')], default='bank', max_length=10),
        ),
    ]
