# Generated by Django 5.1.5 on 2025-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_refund_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='bank_name',
            field=models.CharField(choices=[('KBANK', 'ธนาคารกสิกรไทย'), ('BBL', 'ธนาคารกรุงเทพ'), ('KTB', 'ธนาคารกรุงไทย'), ('GSB', 'ธนาคารออมสิน')], default='bank', max_length=10),
        ),
    ]
