# Generated by Django 5.1.5 on 2025-02-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_refund_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('KBANK', 'ธนาคารกสิกรไทย'), ('BBL', 'ธนาคารกรุงเทพ'), ('KTB', 'ธนาคารกรุงไทย'), ('GSB', 'ธนาคารออมสิน')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Account'), ('promptpay', 'PromptPay')], max_length=10, null=True),
        ),
    ]
